### ISSUE TITLE
About the environment variables

### ISSUE THREAD

**Issue by annuus113** [HewlettPackard/swarm-learning#121]
Hello, my problem is that I can't find the file to configure these environment variables, such as SWARM_LOOPBACK and SL_WAIT_FOR_FULL_QUORUM_SECONDS.

**Comment by IMOKURI** [comment]
It is better to specify the environment variables in the SWOP Profile.

It should be noted that the place to specify the variables is different between SL and ML. SL uses `slenvvvars` and ML uses `usrenvvars`.

I think `SWARM_LOOPBACK` is an environment variable for ML and `SL_WAIT_FOR_FULL_QUORUM_SECONDS` is for SL.

For example,

``` yaml
      slenvvars:
        - SL_WAIT_FOR_FULL_QUORUM_SECONDS: 600
      usrenvvars:
        - SWARM_LOOPBACK: True
```

https://github.com/HewlettPackard/swarm-learning/blob/master/docs/SWOP-profile-schema.yaml
